services:
  - type: web
    name: talonvigil-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11
    preInstall:
      apt-get update && apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev
